#!/usr/bin/python
# -*- coding: utf-8 -*-

__author__ = "Lucas Miguel S Ponce"
__email__  = "lucasmsp@gmail.com"

from pycompss.api.task          import task
from pycompss.api.parameter     import *

import numpy as np
import pandas as pd



def FeatureAssemblerOperation(df, cols, name, numFrag):
    """
    Feature Assembler is a transformer that combines a given list of columns
    into a single vector column. It is useful for combining raw features and
    features generated by different feature transformers into a single feature
    vector, in order to train ML models.

    Feature Assembler accepts the following input column types: all numeric
    types, boolean type, and vector type. In each row, the values of the
    input columns will be concatenated into a vector in the specified order.

    :param df:      Input DataFrame
    :param cols:    List of columns's name to be assembled
    :param name:    Name of the new column

    """
    for i in range(numFrag):
        df[i] = FeatureAssemble_parallel(df[i],cols,name)
    return df

@task(returns=list)
def FeatureAssemble_parallel(df,cols,name):
    df[name] =  df[cols].values.tolist()
    return df
